---
version: '2'
services:
  kafka-load:
    build: kafka-load
    image: kafka-load:1.0
    container_name: kafka-load
    environment:
      Brokers: "kafka-2d779090-jrt13a-c2b8.aivencloud.com:22526"
      TopicName: rawdata
      KafkaThreads: 2
      RunSeconds: 60
